alias ..="cd .."
alias a="git add -A"
alias c="git commit -m"
alias co="git checkout"
alias d="git diff"
alias ds="git diff --staged"
alias gl="git log"
alias grep="grep --colour=auto"
alias h+="hg qpush -a --keep-changes"
alias h-="hg qpop -a --keep-changes"
alias ha="hg addremove"
alias hc="hg commit -m "
alias hd="hg diff"
alias hl="hg log -l 15 --stat --no-merges --removed"
alias hm="hg merge; hc 'merge'"
alias hp="hg push"
alias hpp="hg pull -u"
alias hs="hg status"
alias hsr="hg serve -p 8080"
alias hu="hg update"
alias ll="ls -halG"
alias ls="ls -hG"
alias npm2="npm --registry http://registry.npmjs.eu/"
alias npmp="npm version patch; p; pt; npm publish;"
alias npmm="npm version minor; p; pt; npm publish;"
alias nw="/Applications/node-webkit.app/Contents/MacOS/node-webkit"
alias p="git push"
alias pp="git pull"
alias pt="git push --tags"
alias r="fc -s"
alias s="git status"
alias sw="sass --watch --sourcemap"
alias tidy5="~/Documents/vendor/tidy-html5/bin/tidy -i --indent-spaces 4 -w --drop-empty-elements false "
alias top="top -ocpu"

export EDITOR="/usr/local/bin/mate -w"
export PATH="/usr/local/bin:$PATH"

[[ -s ~/Documents/vendor/z/z.sh ]] && source ~/Documents/vendor/z/z.sh

source ~/.git-completion.bash

shopt -s globstar
